djbraintree/urls.py
# -*- coding: utf-8 -*-
"""
Wire this into the root URLConf this way::

    url(r'^braintree/', include('djbraintree.urls', namespace="djbraintree")),
    # url can be changed
    # Call to 'djbraintree.urls' and 'namespace' must stay as is

Call it from reverse()::

    reverse("djbraintree:subscribe")

Call from url tag::

    {% url 'djbraintree:subscribe' %}

"""

from __future__ import unicode_literals
from django.conf.urls import url

from . import settings as app_settings
from . import views


urlpatterns = [

    # HTML views
    url(
        r"^$",
        views.AccountView.as_view(),
        name="account"
    ),
    url(
        r"^subscribe/$",
        views.SubscribeView.as_view(),
        name="subscribe"
    ),
    url(
        r"^confirm/(?P<plan>.+)$",
        views.ConfirmFormView.as_view(),
        name="confirm"
    ),
    url(
        r"^change/plan/$",
        views.ChangePlanView.as_view(),
        name="change_plan"
    ),
    url(
        r"^change/cards/$",
        views.ChangeCardView.as_view(),
        name="change_card"
    ),
    url(
        r"^cancel/subscription/$",
        views.CancelSubscriptionView.as_view(),
        name="cancel_subscription"
    ),
    url(
        r"^history/$",
        views.HistoryView.as_view(),
        name="history"
    ),


    # Web services
    url(
        r"^a/sync/history/$",
        views.SyncHistoryView.as_view(),
        name="sync_history"
    ),

    # Webhook
    url(
        app_settings.DJBRAINTREE_WEBHOOK_URL,
        views.WebHook.as_view(),
        name="webhook"
    ),
]

djbraintree/templates/djbraintree/account.html
{% extends "djbraintree/base.html" %}

{% block title %}Accounts Dashboard{% endblock title %}

{% block content %}
{{ block.super }}
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            {% include "djbraintree/includes/_subscription_status.html" %}
            <h2>Account Information</h2>
        </div>
    </div>
    <div class="row">
        {% if customer.has_valid_card %}
            <div class="col-xs-4">
                <p>
                    Credit Card on file.
                    <a class="btn btn-info" data-toggle="modal" href="#show-card">Show Card</a>
                </p>
            </div>

            <div class="col-xs-4">
                <p>
                    <a class="btn btn-primary pull-right" href="{% url 'djbraintree:change_card' %}">Change Card</a>
                </p>
            </div>
        {% else %}
            <div class="col-xs-4" style="margin-bottom:10px;">
                <p>
                    <a class="btn btn-primary pull-left" href="{% url 'djbraintree:change_card' %}">Add Card</a>
                </p>
            </div>
        {% endif %}
    </div>


    {% if subscription.is_status_current and not subscription.is_status_temporarily_current %}
        <p>Next billed on {{ subscription.current_period_end|date }}.</p>
        <p>You can <a href="{% url 'djbraintree:subscribe' %}">change</a> your plan
        or <a href="{% url 'djbraintree:cancel_subscription' %}">cancel</a> your subscription.
        </p>
    {% else %}
        <p>You can <a href="{% url 'djbraintree:subscribe' %}">subscribe</a>.</p>
    {% endif %}
    <p>Or consult your <a href="{% url 'djbraintree:history' %}">payment history</a>.</p>

    {% if plans %}
        {# Show available plans #}
        <div class="row">
            <div class="col-xs-12">
                <h2>Subscription</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Plan</th>
                            <th>Interval</th>
                            <th>Description</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for plan in plans %}
                        <tr {% if plan.plan == subscription.plan %}
                            {% if subscription.is_status_current and not subscription.is_status_temporarily_current and subscription.status != subscription.STATUS_TRIALING %}
                                class="success"
                            {% elif subscription.is_status_temporarily_current or subscription.status == subscription.STATUS_TRIALING %}
                                class="warning"
                            {% endif %}
                        {% endif %}>
                            <td>{{ plan.name }}</td>
                            <td>{{ plan.interval.title }}ly</td>
                            <td>{{ plan.description }}</td>
                            <td>
                                {% if plan.plan == subscription.plan and subscription.status != subscription.STATUS_CANCELLED %}
                                    <strong>Your plan</strong>
                                {% else %}
                                    Not your plan
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% else %}
        {# No plans so just show payment history #}
        {% include "djbraintree/includes/_history_table.html" %}
    {% endif %}
</div>

  <!-- Modal for showing card -->
  <div class="modal fade" id="show-card">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Card on File</h4>
        </div>
        <div class="modal-body">
            <p><strong>Type:</strong> {{ customer.card_kind }}</p>
            <p><strong>Last 4 Digits:</strong> {{ customer.card_last_4 }}</p>
            <p><small>For security, your card information is stored on <a href="https://stripe.com">stripe.com</a>.</small></p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

{% endblock content %}

{% block javascript %}
{{ block.super }}
{% if plans %}
    <script>
        $(function() {
            $.post("{% url 'djbraintree:sync_history' %}", function(data) {
                $('#history-table').html(data);
            });
        });
    </script>
{% else %}
    <script>
        $(function() {
            $.post("{% url 'djbraintree:sync_history' %}", function(data) {
                $('#history-table').html(data);
                $('.in-progress-gif').hide();
            });
        });
    </script>
{% endif %}
{% endblock javascript %}

djbraintree/templates/djbraintree/base.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <!-- Modal for server update -->
  <div class="modal fade" id="in-progress">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Server Update In-Progress <img class="pull-right" src="{% static 'img/in-progress.gif' %}" /></h4>
        </div>
        <div class="modal-body">
            <div class="progress">
                <div class="progress-bar" style="width: 0%;"></div>
            </div>
        </div>

      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
{% endblock %}

djbraintree/templates/djbraintree/cancel_subscription.html
{% extends "djbraintree/base.html" %}

{% block title %}Cancel Subscription{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
        <ul class="breadcrumb">
          <li><a href="{% url 'djbraintree:account' %}">Home</a></li>
          <li class="active">Cancel Subscription</li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h2>Cancel Subscription</h2>
        {% if not customer.current_subscription %}
            <p>You have no subscription on file.</p>
            <p>See your <a href="{% url 'djbraintree:account' %}">account status</a> or better yet, <a href="{% url 'djbraintree:subscribe' %}">subscribe</a>.</p>
        {% elif customer.current_subscription.status == customer.current_subscription.STATUS_CANCELLED %}
            <p>Your subscription has already been canceled.</p>
            <p>See your <a href="{% url 'djbraintree:account' %}">account status</a> or better yet, get a <a href="{% url 'djbraintree:subscribe' %}">fresh subscription</a>.</p>
        {% elif customer.current_subscription.is_status_temporarily_current %}
            <p>Your subscription has already been canceled.</p>
            <p>However, you can still use the site for another {{ customer.current_subscription.current_period_end|timeuntil }}.</p>
        {% else %}
            <p class="lead">
              Are you sure you want to cancel your subscription?
            </p>
            {% block cancellation_ramifications %}
            <h3>What you lose by cancelling your subscription:</h3>
            <ul>
              <li>Access to subscription-only content.</li>
              <li>Ability to use subscription-only features.</li>
            </ul>
            {% endblock cancellation_ramifications %}

            <h3>Are you sure you want to cancel?</h3>
            <form action="{% url 'djbraintree:cancel_subscription' %}" method="post" id="cancel-form">
                {% csrf_token %}
                <a href="{% url 'djbraintree:account' %}" class="btn btn-primary">I change my mind!</a>
                <button class="btn btn-danger">Cancel my subscription!</button>
            </form>
        {% endif %}
    </div>
</div>
{% endblock content %}

djbraintree/templates/djbraintree/change_card.html
{% extends "djbraintree/base.html" %}

{% block title %}Change Card{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
        <ul class="breadcrumb">
          <li><a href="{% url 'djbraintree:account' %}">Home</a></li>
          <li class="active">Change Card</li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h2>Current Card</h2>
        <p class="lead">
            {% if customer.card_kind and customer.card_last_4 %}
                Current card on file is a <strong>{{ customer.card_kind }}</strong>
                ending in the digits <strong>{{ customer.card_last_4 }}</strong>.
            {% else %}
                You do not currently have a card on file.
            {% endif %}
        </p>
        
        {% if braintree_error %}
            <div class="alert alert-error">{{ braintree_error }}</div>
        {% endif %}
        
            
        <form action="{% url 'djbraintree:change_card' %}" method="POST" id="change-card-form">
        {% csrf_token %}
          <span class="payment-errors"></span>

          <div class="form-row">
            <label>
              <span>Card Number</span>
              <input type="text" size="20" pattern="\d*" autocomplete="off" data-stripe="number"/>
            </label>
          </div>

          <div class="form-row">
            <label>
              <span>CVC</span>
              <input type="text" size="4" pattern="\d*" data-stripe="cvc"/>
            </label>
          </div>

          <div class="form-row">
            <label>
              <span>Expiration (MM/YYYY)</span>
              <input type="text" size="2" pattern="\d*" autocomplete="off" data-stripe="exp-month"/>
            </label>
            <span> / </span>
            <input type="text" size="4" pattern="\d*" autocomplete="off" data-stripe="exp-year"/>
          </div>

          <button class="btn btn-primary change-card" type="submit">Change Card</button>
        </form>
    </div>
</div>
{% endblock content %}


{% block javascript %}
{{ block.super }}
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  // This identifies your website in the createToken call below
  Braintree.setPublishableKey('{{ BRAINTREE_PUBLIC_KEY }}');
  jQuery(function($) {
    $('#change-card-form').submit(function(event) {
        var $form = $(this);

        // Disable the submit button to prevent repeated clicks
        $form.find('button').prop('disabled', true);

        Braintree.card.createToken($form, stripeResponseHandler);

        // Prevent the form from submitting with the default action
        return false;
    });

    var stripeResponseHandler = function(status, response) {
      var $form = $('#change-card-form');

      if (response.error) {
        // Show the errors on the form
        $form.find('.payment-errors').text(response.error.message);
        $form.find('button').prop('disabled', false);
      } else {
        // token contains id, last4, and card type
        var token = response.id;
        // Insert the token into the form so it gets submitted to the server
        $form.append($('<input type="hidden" name="stripe_token" />').val(token));
        // and submit
        $form.get(0).submit();
      }
    };
});
</script>

{% endblock javascript %}

djbraintree/templates/djbraintree/confirm_form.html
{% extends "djbraintree/base.html" %}
{% load static djbraintree_tags %}

{% block title %}Choose a Subscription{% endblock title %}

{% block content %}
{{ block.super }}
<ul class="breadcrumb">
    <li><a href="{% url 'djbraintree:account' %}">Home</a></li>
    <li><a href="{% url 'djbraintree:subscribe' %}">Subscription</a></li>
    <li class="active">Confirm</li>
</ul>
<h2>Confirm your Subscription</h2>
{% if error %}
    <div class="alert alert-error">{{ error }}</div>
{% endif %}
{% if view.error %}
    <div class="alert alert-error">{{ view.error }}</div>
{% endif %}

<div class="row">
    <div class="col-xs-12">
        <form
        {% if not customer.current_subscription or customer.current_subscription.status == CurrentSubscription.STATUS_CANCELLED %}
            action="{% url 'djbraintree:confirm' plan=plan.plan %}" class="djbraintree-subscribe"
            data-key="{{ BRAINTREE_PUBLIC_KEY }}"
            data-amount="{{ plan.price }}"
            data-name="{{ plan.name }}"
            data-description="{{ plan.description }}"
        {% else %}
            data-stripe-key="{{ BRAINTREE_PUBLIC_KEY }}"
            action="{% url 'djbraintree:change_plan' %}" class="djbraintree-change-plan"
        {% endif %}
        method="POST">

        {% csrf_token %}
        <input type="hidden" name="plan" value="{{ plan.plan }}" />
        <input name="stripe_token" type="hidden" />

        <!-- disable this when clicked -->
        <button type="submit" class="btn btn-primary">
            {% with image=plan.image|default:"img/default-plan-image.png" %}
                <img src="{% static image %}" class="img-thumbnail" />
            {% endwith %}
            <h3>{{ plan.name }}</h3>
            <p>{{ plan.description }}</p>
        </button>

        {% if not customer.current_subscription or customer.current_subscription.status == CurrentSubscription.STATUS_CANCELLED %}
          <!-- do nothing -->
        {% elif customer.current_subscription.plan == plan.plan %}
            <h4>Your Current Plan</h4>
        {% elif customer.current_subscription.amount < plan.price|djdiv:100 %}
            <h4>Upgrade</h4>
        {% elif customer.current_subscription.amount > plan.price|djdiv:100 %}
            <h4>Downgrade</h4>
        {% endif %}
        </form>
    </div>
</div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
<script src="https://checkout.stripe.com/v2/checkout.js"></script>
<script text="text/javascript">
    $(function() {
        $('body').on("click", '.djbraintree-subscribe button[type=submit]', function(e) {
            e.preventDefault();
            // retrieve current $(".djbraintree-subscribe")
            var $form = $(e.target).parents('form'),
            token = function(res) {
                $form.find("input[name=stripe_token]").val(res.id);
                $("button[type=submit]").attr("disabled", "true");
                $('#in-progress').modal({"keyboard": false})
                $('.progress-bar').animate({width:'+=100%'}, 2000);
                $form.trigger("submit");
            };
            BraintreeCheckout.open({
                key: "{{ BRAINTREE_PUBLIC_KEY }}",
                name: 'Payment Method',
                panelLabel: 'Add Payment Method',
                token: token
            });
            return false;
        });
        {% if PLAN_LIST|length > 1 %}
        $('.djbraintree-change-plan').click(function(e){
            $("button[type=submit]").attr("disabled", "true");
            $('#in-progress').modal({"keyboard": false})
            $('.progress-bar').animate({width:'+=100%'}, 2000);
            var $form = $(this);
            $form.trigger("submit");
        });
        {% endif %}
    });
</script>
{% endblock javascript %}

djbraintree/templates/djbraintree/history.html
{% extends "djbraintree/base.html" %}

{% block title %}Payment History{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-xs-12">
        <ul class="breadcrumb">
            <li><a href="{% url 'djbraintree:account' %}">Home</a></li>
            <li class="active">Payment History</li>
        </ul>
        {% include "djbraintree/includes/_history_table.html" %}
    </div>
</div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
<script>
    $(function() {
        $.post("{% url 'djbraintree:sync_history' %}", function(data) {
            $('#history-table').html(data);
            $('.in-progress-gif').hide();
        });
    });
</script>
{% endblock javascript %}

djbraintree/templates/djbraintree/stripe_input.html
<input type="{{ type }}" {% if value %} value="{{ value }}"{% endif %}{% if required %} required{% endif %}{% include "floppyforms/attrs.html" %}{% if datalist %} list="{{ attrs.id }}_list"{% endif %}>{% if datalist %}
<datalist id="{{ attrs.id }}_list">{% for item in datalist %}
    <option value="{{ item }}">{% endfor %}
</datalist>{% endif %}

djbraintree/templates/djbraintree/subscribe.html
{% extends "djbraintree/base.html" %}
{% load static djbraintree_tags %}

{% block title %}Choose a Subscription{% endblock title %}

{% block content %}
{{ block.super }}
<ul class="breadcrumb">
  <li><a href="{% url 'djbraintree:account' %}">Home</a></li>
  <li class="active">Subscription</li>
</ul>
<h2>Choose a Subscription</h2>

{% if error %}
    <div class="alert alert-error">{{ error }}</div>
{% endif %}
{% if view.error %}
    <div class="alert alert-error">{{ view.error }}</div>
{% endif %}

<div class="row">
    {% for plan in PLAN_LIST %}
      {% with plan_count=PLAN_LIST|length %}
        <div class="col-xs-{{ 12|djdiv:plan_count|floatformat }}">
      {% endwith %}
            {% if customer.current_subscription.plan == plan.plan and customer.current_subscription.status != CurrentSubscription.STATUS_CANCELLED %}
            <div class="btn btn-default disabled">
            {% else %}
            <a class="btn btn-primary" href="{% url 'djbraintree:confirm' plan=plan.plan %}" role="button">
            {% endif %}
                  {% with image=plan.image|default:"img/default-plan-image.png" %}
                    <img src="{% static image %}" class="img-thumbnail" />
                  {% endwith %}
                  <h3>{{ plan.name }}</h3>
                  <p>{{ plan.description }}</p>
            {% if customer.current_subscription.plan == plan.plan and customer.current_subscription.status != CurrentSubscription.STATUS_CANCELLED %}
            </div>
            <h4>Your Current Plan</h4>
            {% else %}
            </a>
              {% if customer.current_subscription.amount < plan.price|djdiv:100 %}
                <h4>Upgrade</h4>
              {% elif customer.current_subscription.amount > plan.price|djdiv:100 %}
                <h4>Downgrade</h4>
              {% endif %}
            {% endif %}
        </div>
    {% endfor %}
</div>

{% endblock content %}